# Generated by Django 5.0.14 on 2026-04-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                ("snapshot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "total_active_jobs",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of active job postings",
                        verbose_name="total active jobs",
                    ),
                ),
                (
                    "jobs_posted_last_7d",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs posted in last 7 days",
                        verbose_name="jobs posted (7d)",
                    ),
                ),
                (
                    "jobs_posted_last_30d",
                    models.IntegerField(
                        default=0,
                        help_text="Jobs posted in last 30 days",
                        verbose_name="jobs posted (30d)",
                    ),
                ),
                (
                    "total_companies",
                    models.IntegerField(
                        default=0,
                        help_text="Unique companies with job postings",
                        verbose_name="total companies",
                    ),
                ),
                (
                    "total_skills_tracked",
                    models.IntegerField(
                        default=0,
                        help_text="Total canonical skills in system",
                        verbose_name="skills tracked",
                    ),
                ),
                (
                    "skills_in_demand",
                    models.IntegerField(
                        default=0,
                        help_text="Skills appearing in active jobs",
                        verbose_name="skills in demand",
                    ),
                ),
                (
                    "avg_salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="average min salary",
                    ),
                ),
                (
                    "avg_salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="average max salary",
                    ),
                ),
                (
                    "median_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="median salary",
                    ),
                ),
                (
                    "remote_jobs_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of remote-friendly jobs",
                        verbose_name="remote jobs %",
                    ),
                ),
                (
                    "experience_distribution",
                    models.JSONField(
                        default=dict,
                        help_text="Job count by experience level",
                        verbose_name="experience distribution",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(auto_now_add=True, verbose_name="snapshot date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "dashboard snapshot",
                "verbose_name_plural": "dashboard snapshots",
                "db_table": "dashboard_snapshots",
                "ordering": ["-snapshot_date"],
                "get_latest_by": "snapshot_date",
            },
        ),
        migrations.CreateModel(
            name="JobCategorySnapshot",
            fields=[
                ("snapshot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(
                        help_text='Job category (e.g., "Backend Development")',
                        max_length=100,
                        verbose_name="category name",
                    ),
                ),
                ("job_count", models.IntegerField(default=0, verbose_name="job count")),
                (
                    "job_count_change_7d",
                    models.FloatField(
                        blank=True, null=True, verbose_name="change (7d) %"
                    ),
                ),
                (
                    "avg_salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="avg min salary",
                    ),
                ),
                (
                    "avg_salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="avg max salary",
                    ),
                ),
                (
                    "experience_breakdown",
                    models.JSONField(default=dict, verbose_name="experience breakdown"),
                ),
                (
                    "top_skills",
                    models.JSONField(default=list, verbose_name="top skills"),
                ),
                (
                    "snapshot_date",
                    models.DateField(auto_now_add=True, verbose_name="snapshot date"),
                ),
            ],
            options={
                "verbose_name": "job category snapshot",
                "verbose_name_plural": "job category snapshots",
                "db_table": "job_category_snapshots",
                "ordering": ["-job_count"],
                "unique_together": {("category_name", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="SalarySnapshot",
            fields=[
                ("snapshot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "job_title_normalized",
                    models.CharField(
                        help_text='Normalized job title (e.g., "Backend Developer")',
                        max_length=200,
                        verbose_name="job title",
                    ),
                ),
                (
                    "job_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of jobs with salary data",
                        verbose_name="job count",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="min salary",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="max salary",
                    ),
                ),
                (
                    "salary_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="avg salary",
                    ),
                ),
                (
                    "salary_median",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="median salary",
                    ),
                ),
                (
                    "salary_p25",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="25th percentile",
                    ),
                ),
                (
                    "salary_p75",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="75th percentile",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UZS", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("all", "All levels"),
                            ("no_experience", "No Experience"),
                            ("junior", "Junior"),
                            ("mid", "Mid-level"),
                            ("senior", "Senior"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="experience level",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(auto_now_add=True, verbose_name="snapshot date"),
                ),
            ],
            options={
                "verbose_name": "salary snapshot",
                "verbose_name_plural": "salary snapshots",
                "db_table": "salary_snapshots",
                "ordering": ["-salary_avg"],
                "unique_together": {
                    ("job_title_normalized", "experience_level", "snapshot_date")
                },
            },
        ),
        migrations.CreateModel(
            name="SkillDemandSnapshot",
            fields=[
                ("snapshot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "job_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of jobs requiring this skill",
                        verbose_name="job count",
                    ),
                ),
                (
                    "demand_rank",
                    models.IntegerField(
                        default=0,
                        help_text="Rank among all skills (1 = most in-demand)",
                        verbose_name="demand rank",
                    ),
                ),
                (
                    "demand_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Normalized demand score (0-100)",
                        verbose_name="demand score",
                    ),
                ),
                (
                    "demand_change_7d",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change in last 7 days",
                        null=True,
                        verbose_name="demand change (7d)",
                    ),
                ),
                (
                    "demand_change_30d",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage change in last 30 days",
                        null=True,
                        verbose_name="demand change (30d)",
                    ),
                ),
                (
                    "avg_salary_with_skill",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="avg salary with skill",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("7d", "Last 7 days"),
                            ("30d", "Last 30 days"),
                            ("90d", "Last 90 days"),
                            ("all", "All time"),
                        ],
                        default="30d",
                        max_length=10,
                        verbose_name="period",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(auto_now_add=True, verbose_name="snapshot date"),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_snapshots",
                        to="skills.skill",
                        verbose_name="skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "skill demand snapshot",
                "verbose_name_plural": "skill demand snapshots",
                "db_table": "skill_demand_snapshots",
                "ordering": ["demand_rank"],
                "indexes": [
                    models.Index(
                        fields=["period", "demand_rank"],
                        name="skill_deman_period_c3470b_idx",
                    ),
                    models.Index(
                        fields=["snapshot_date"], name="skill_deman_snapsho_725f63_idx"
                    ),
                ],
                "unique_together": {("skill", "period", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="SkillTrendHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "week_start",
                    models.DateField(
                        help_text="Start of the week (Monday)",
                        verbose_name="week start",
                    ),
                ),
                ("job_count", models.IntegerField(default=0, verbose_name="job count")),
                (
                    "demand_score",
                    models.FloatField(default=0.0, verbose_name="demand score"),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_history",
                        to="skills.skill",
                        verbose_name="skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "skill trend history",
                "verbose_name_plural": "skill trend history",
                "db_table": "skill_trend_history",
                "ordering": ["-week_start"],
                "indexes": [
                    models.Index(
                        fields=["skill", "week_start"],
                        name="skill_trend_skill_i_a9ad37_idx",
                    )
                ],
                "unique_together": {("skill", "week_start")},
            },
        ),
    ]
