# Generated by Django 5.2.9 on 2026-02-04 12:44
# Modified to handle model move from analytics to skills app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to remove model from Django's state
        # without actually deleting the table (it will be owned by skills app)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MarketTrend',
                ),
            ],
            database_operations=[],  # No database changes - table stays
        ),
    ]
