# Generated by Django 5.0.14 on 2026-03-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recruitersavedsearch",
            new_name="recruiter_s_recruit_e4f0af_idx",
            old_name="rec_saved_srch_rec_idx",
        ),
        migrations.RenameIndex(
            model_name="savedcandidate",
            new_name="recruiter_s_recruit_1d1640_idx",
            old_name="rec_saved_cand_rec_idx",
        ),
    ]
