# Generated by Django 5.0.14 on 2026-04-22 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIdea",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed project description and learning objectives",
                        verbose_name="description",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        help_text="Which career role this project is designed for",
                        max_length=100,
                        verbose_name="target role",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "estimated_hours",
                    models.PositiveIntegerField(
                        help_text="Estimated time to complete (in hours)",
                        verbose_name="estimated hours",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated this idea; only this user can view or use it via the API.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_ideas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "project idea",
                "verbose_name_plural": "project ideas",
                "db_table": "project_ideas",
                "ordering": ["difficulty_level", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSkill",
            fields=[
                (
                    "project_skill_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("core", "Core / Required"),
                            ("secondary", "Secondary / Optional"),
                        ],
                        default="core",
                        max_length=20,
                        verbose_name="importance",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_skills",
                        to="projects.projectidea",
                        verbose_name="project",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_skills",
                        to="skills.skill",
                        verbose_name="skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "project skill",
                "verbose_name_plural": "project skills",
                "db_table": "project_skills",
                "unique_together": {("project", "skill")},
            },
        ),
        migrations.AddField(
            model_name="projectidea",
            name="skills",
            field=models.ManyToManyField(
                related_name="project_ideas",
                through="projects.ProjectSkill",
                to="skills.skill",
            ),
        ),
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "user_project_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to project repository",
                        max_length=500,
                        verbose_name="GitHub URL",
                    ),
                ),
                (
                    "live_demo_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to deployed/live demo",
                        max_length=500,
                        verbose_name="live demo URL",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes, learnings, challenges faced",
                        verbose_name="notes",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_projects",
                        to="projects.projectidea",
                        verbose_name="project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user project",
                "verbose_name_plural": "user projects",
                "db_table": "user_projects",
                "ordering": ["-started_at"],
                "unique_together": {("user", "project")},
            },
        ),
    ]
