# Generated by Django 5.0.14 on 2026-03-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectidea_created_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="projectidea",
            name="proj_idea_owner_created",
        ),
    ]
