# Generated by Django 5.0.14 on 2026-04-22 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                ("cv_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text='CV title for your reference (e.g., "Software Engineer CV")',
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("creative", "Creative"),
                            ("minimalist", "Minimalist"),
                            ("professional", "Professional"),
                        ],
                        default="modern",
                        max_length=20,
                        verbose_name="template type",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian"), ("uz", "Uzbek")],
                        default="en",
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Set as default CV for job applications",
                        verbose_name="default CV",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "db_table": "cvs",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CVSection",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("personal_info", "Personal Information"),
                            ("summary", "Professional Summary"),
                            ("experience", "Work Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("projects", "Projects"),
                            ("certifications", "Certifications"),
                            ("languages", "Languages"),
                            ("awards", "Awards & Achievements"),
                        ],
                        max_length=20,
                        verbose_name="section type",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="Section content in JSON format",
                        verbose_name="content",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which section appears in CV",
                        verbose_name="display order",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Show/hide this section in CV",
                        verbose_name="visible",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_sections",
                        to="cv.cv",
                        verbose_name="CV",
                    ),
                ),
            ],
            options={
                "verbose_name": "CV section",
                "verbose_name_plural": "CV sections",
                "db_table": "cv_sections",
                "ordering": ["cv", "display_order"],
                "unique_together": {("cv", "section_type")},
            },
        ),
    ]
