# Generated by Django 5.2.9 on 2026-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='section_type',
            field=models.CharField(choices=[('personal_info', 'Personal Information'), ('summary', 'Professional Summary'), ('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('languages', 'Languages'), ('awards', 'Awards & Achievements')], max_length=20, verbose_name='section type'),
        ),
    ]
