# Generated by Django 5.0.14 on 2026-04-22 05:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. Enter a valid email address.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional. User phone number.",
                        max_length=20,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian"), ("uz", "Uzbek")],
                        default="en",
                        help_text="User preferred interface language.",
                        max_length=2,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("developer", "Developer"),
                            ("recruiter", "Recruiter"),
                        ],
                        db_index=True,
                        default="developer",
                        help_text="Developer (talent) or recruiter (employer) account; set at registration.",
                        max_length=20,
                        verbose_name="user type",
                    ),
                ),
                (
                    "recruiter_plan",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro")],
                        default="free",
                        help_text="Subscription tier for recruiter accounts; ignored for developers.",
                        max_length=10,
                        verbose_name="recruiter plan",
                    ),
                ),
                (
                    "profile_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has completed initial profile setup.",
                        verbose_name="profile completed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("account_created", "Account created"),
                            ("profile_setup", "Profile set up"),
                            ("cv_uploaded", "CV uploaded"),
                            ("skill_added", "Skill added"),
                            ("skills_bulk_added", "Skills bulk added"),
                            ("skill_removed", "Skill removed"),
                            ("gap_analyzed", "Skill gap analyzed"),
                            ("gap_status", "Skill gap updated"),
                            ("gaps_cleared", "Skill gaps cleared"),
                            ("roadmap_created", "Learning roadmap created"),
                            ("roadmap_progress", "Roadmap progress"),
                        ],
                        max_length=32,
                        verbose_name="activity type",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "link_path",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="link path"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activities",
                "db_table": "user_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "current_job_position",
                    models.CharField(
                        blank=True,
                        help_text="User current job title or position.",
                        max_length=200,
                        null=True,
                        verbose_name="current job position",
                    ),
                ),
                (
                    "desired_role",
                    models.CharField(
                        blank=True,
                        help_text="Target career role user wants to achieve.",
                        max_length=200,
                        null=True,
                        verbose_name="desired role",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("junior", "Junior"),
                            ("mid", "Mid-level"),
                            ("senior", "Senior"),
                            ("lead", "Lead/Principal"),
                        ],
                        default="beginner",
                        help_text="User current experience level in IT.",
                        max_length=20,
                        verbose_name="experience level",
                    ),
                ),
                (
                    "cv_file_path",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded CV file (PDF or DOCX).",
                        null=True,
                        upload_to="cvs/%Y/%m/",
                        verbose_name="CV file",
                    ),
                ),
                (
                    "profile_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("cv_upload", "CV Upload"),
                            ("assessment", "Career Assessment"),
                        ],
                        default="manual",
                        help_text="How the profile was created.",
                        max_length=20,
                        verbose_name="profile source",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="User biography or summary.",
                        null=True,
                        verbose_name="bio",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/%Y/%m/",
                        verbose_name="profile picture",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="User city or region.",
                        max_length=100,
                        null=True,
                        verbose_name="location",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="GitHub URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Portfolio URL"
                    ),
                ),
                (
                    "open_to_recruiters",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this developer profile may appear in recruiter search (subject to product rules).",
                        verbose_name="open to recruiters",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Employer or agency name; used for recruiter accounts.",
                        max_length=255,
                        verbose_name="company name",
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True, null=True, verbose_name="company website"
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        blank=True,
                        help_text="Short company overview for candidate-facing pages.",
                        verbose_name="company description",
                    ),
                ),
                (
                    "recruiter_title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. HR Business Partner, Technical Recruiter.",
                        max_length=200,
                        verbose_name="recruiter title at company",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type", "-created_at"], name="users_user_ty_28135a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-created_at"], name="user_activi_user_id_47a698_idx"
            ),
        ),
    ]
