# Generated by Cursor on 2026-04-23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # This column existed in some DBs; payments are tracked in apps.payments now.
                "ALTER TABLE users DROP COLUMN IF EXISTS has_paid_for_cv;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        )
    ]

