# Generated by Cursor on 2026-04-23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_has_paid_for_cv"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Legacy payment/subscription fields previously stored on users table.
                # Payments are now tracked in apps.payments (Customer/Subscription/Payment).
                "ALTER TABLE users DROP COLUMN IF EXISTS subscription_status;",
                "ALTER TABLE users DROP COLUMN IF EXISTS subscription_start;",
                "ALTER TABLE users DROP COLUMN IF EXISTS subscription_end;",
                "ALTER TABLE users DROP COLUMN IF EXISTS subscription_current_period_start;",
                "ALTER TABLE users DROP COLUMN IF EXISTS subscription_current_period_end;",
                "ALTER TABLE users DROP COLUMN IF EXISTS stripe_customer_id;",
                "ALTER TABLE users DROP COLUMN IF EXISTS stripe_subscription_id;",
                "ALTER TABLE users DROP COLUMN IF EXISTS stripe_payment_intent_id;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        )
    ]

