# Generated by Django 5.0.14 on 2026-03-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_activity"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="user_activi_user_id_47a698_idx",
            old_name="ua_user_created_desc",
        ),
    ]
