# Generated by Cursor on 2026-04-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_legacy_payment_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_codes",
            },
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(fields=["user", "-created_at"], name="password_re_user_id_6afde2_idx"),
        ),
    ]

