# Generated by Django 5.0.14 on 2026-03-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_marketplace_user_and_profile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_ty_28135a_idx",
            old_name="users_user_type_cr_idx",
        ),
    ]
