# Generated by Django 5.0.14 on 2026-04-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_password_reset_code"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresetcode",
            new_name="password_re_user_id_955e16_idx",
            old_name="password_re_user_id_6afde2_idx",
        ),
    ]
