# Generated by Django 5.2.9 on 2026-01-31 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='name (English)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='name (Russian)')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='name (Uzbek)')),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('design', 'Design'), ('management', 'Management'), ('business', 'Business'), ('creative', 'Creative')], max_length=20, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'interest',
                'verbose_name_plural': 'interests',
                'db_table': 'interests',
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('user_interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='interests.interest', verbose_name='interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user interest',
                'verbose_name_plural': 'user interests',
                'db_table': 'user_interests',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
