# Generated by Django 5.0.14 on 2026-03-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="threadmessage",
            new_name="thread_mess_thread__48e1c5_idx",
            old_name="thread_mess_thread__b8da2e_idx",
        ),
    ]
