# Generated by Django 5.2.9 on 2026-01-26 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('interest', 'Interest & Passion'), ('work_environment', 'Work Environment'), ('work_style', 'Work Style'), ('skills', 'Skills & Strengths'), ('goals', 'Career Goals')], help_text='Question category.', max_length=50, verbose_name='category')),
                ('question_text_en', models.TextField(help_text='Question text in English.', verbose_name='question text (English)')),
                ('question_text_ru', models.TextField(help_text='Question text in Russian.', verbose_name='question text (Russian)')),
                ('question_text_uz', models.TextField(help_text='Question text in Uzbek.', verbose_name='question text (Uzbek)')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('rating', 'Rating Scale')], default='single_choice', help_text='Type of question.', max_length=20, verbose_name='question type')),
                ('sequence_order', models.IntegerField(help_text='Order in which question appears (1, 2, 3...).', verbose_name='sequence order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is currently active.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'career question',
                'verbose_name_plural': 'career questions',
                'db_table': 'career_questions',
                'ordering': ['sequence_order'],
                'indexes': [models.Index(fields=['category'], name='career_ques_categor_987846_idx'), models.Index(fields=['sequence_order'], name='career_ques_sequenc_1ae44e_idx'), models.Index(fields=['is_active'], name='career_ques_is_acti_ac0e27_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text='Role name in English (e.g., "Frontend Developer").', max_length=200, unique=True, verbose_name='role name (English)')),
                ('role_name_ru', models.CharField(help_text='Role name in Russian.', max_length=200, verbose_name='role name (Russian)')),
                ('role_name_uz', models.CharField(help_text='Role name in Uzbek.', max_length=200, verbose_name='role name (Uzbek)')),
                ('category', models.CharField(choices=[('development', 'Software Development'), ('data', 'Data & Analytics'), ('design', 'Design & UX'), ('infrastructure', 'Infrastructure & DevOps'), ('security', 'Security'), ('management', 'Management & Product'), ('other', 'Other')], default='development', help_text='Role category.', max_length=50, verbose_name='category')),
                ('description_en', models.TextField(help_text='Role description in English.', verbose_name='description (English)')),
                ('description_ru', models.TextField(help_text='Role description in Russian.', verbose_name='description (Russian)')),
                ('description_uz', models.TextField(help_text='Role description in Uzbek.', verbose_name='description (Uzbek)')),
                ('average_salary_uzb', models.DecimalField(blank=True, decimal_places=2, help_text='Average salary in Uzbekistan (UZS).', max_digits=12, null=True, verbose_name='average salary (UZS)')),
                ('difficulty_level', models.CharField(choices=[('beginner_friendly', 'Beginner Friendly'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Entry difficulty for beginners.', max_length=30, verbose_name='difficulty level')),
                ('demand_score', models.IntegerField(default=5, help_text='Market demand score (1-10).', verbose_name='demand score')),
                ('work_alone_score', models.IntegerField(default=5, help_text='How much solo work (1-10).', verbose_name='work alone score')),
                ('work_team_score', models.IntegerField(default=5, help_text='How much team work (1-10).', verbose_name='work team score')),
                ('creative_score', models.IntegerField(default=5, help_text='How creative the role is (1-10).', verbose_name='creative score')),
                ('analytical_score', models.IntegerField(default=5, help_text='How analytical the role is (1-10).', verbose_name='analytical score')),
                ('remote_friendly', models.BooleanField(default=True, help_text='Whether role allows remote work.', verbose_name='remote friendly')),
                ('typical_learning_months', models.IntegerField(default=6, help_text='Typical time to become job-ready (months).', verbose_name='typical learning time (months)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'career role',
                'verbose_name_plural': 'career roles',
                'db_table': 'career_roles',
                'ordering': ['role_name'],
                'indexes': [models.Index(fields=['category'], name='career_role_categor_a2a2f6_idx'), models.Index(fields=['demand_score'], name='career_role_demand__4709f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text_en', models.CharField(help_text='Option text in English.', max_length=500, verbose_name='option text (English)')),
                ('option_text_ru', models.CharField(help_text='Option text in Russian.', max_length=500, verbose_name='option text (Russian)')),
                ('option_text_uz', models.CharField(help_text='Option text in Uzbek.', max_length=500, verbose_name='option text (Uzbek)')),
                ('option_value', models.CharField(help_text='Internal value for matching logic.', max_length=100, verbose_name='option value')),
                ('display_order', models.IntegerField(help_text='Order in which option is displayed.', verbose_name='display order')),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier for UI display.', max_length=50, null=True, verbose_name='icon name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='career.careerquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'question option',
                'verbose_name_plural': 'question options',
                'db_table': 'question_options',
                'ordering': ['question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='RoleMatchingRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_weight', models.IntegerField(default=5, help_text='Importance of this match (1-10).', verbose_name='match weight')),
                ('match_type', models.CharField(choices=[('positive', 'Positive Match'), ('negative', 'Negative Match'), ('required', 'Required/Critical')], default='positive', help_text='Type of match.', max_length=20, verbose_name='match type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='career.questionoption', verbose_name='question option')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='career.careerrole', verbose_name='role')),
            ],
            options={
                'verbose_name': 'role matching rule',
                'verbose_name_plural': 'role matching rules',
                'db_table': 'role_matching_rules',
                'ordering': ['role', '-match_weight'],
            },
        ),
        migrations.CreateModel(
            name='UserCareerAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_data', models.JSONField(help_text='Complete assessment answers as JSON.', verbose_name='assessment data')),
                ('recommended_roles', models.JSONField(help_text='AI-recommended roles with scores.', verbose_name='recommended roles')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='completed at')),
                ('selected_role', models.ForeignKey(blank=True, help_text='Role user finally selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='career.careerrole', verbose_name='selected role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_assessments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user career assessment',
                'verbose_name_plural': 'user career assessments',
                'db_table': 'user_career_assessments',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, help_text='Text answer for open-ended questions.', null=True, verbose_name='answer text')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='answered at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='career.careerquestion', verbose_name='question')),
                ('selected_option', models.ForeignKey(blank=True, help_text='Selected option (for single choice).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='career.questionoption', verbose_name='selected option')),
                ('selected_options', models.ManyToManyField(blank=True, help_text='Multiple selected options (for multiple choice).', related_name='multi_selections', to='career.questionoption', verbose_name='selected options')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='career.usercareerassessment', verbose_name='assessment')),
            ],
            options={
                'verbose_name': 'assessment answer',
                'verbose_name_plural': 'assessment answers',
                'db_table': 'assessment_answers',
                'ordering': ['assessment', 'question__sequence_order'],
            },
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'display_order'], name='question_op_questio_bd82b4_idx'),
        ),
        migrations.AddIndex(
            model_name='rolematchingrule',
            index=models.Index(fields=['role'], name='role_matchi_role_id_9ba5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='rolematchingrule',
            index=models.Index(fields=['question_option'], name='role_matchi_questio_77b265_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerassessment',
            index=models.Index(fields=['user'], name='user_career_user_id_3dd253_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerassessment',
            index=models.Index(fields=['completed_at'], name='user_career_complet_25deaa_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentanswer',
            index=models.Index(fields=['assessment'], name='assessment__assessm_51fe82_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentanswer',
            index=models.Index(fields=['question'], name='assessment__questio_0ad0bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentanswer',
            unique_together={('assessment', 'question')},
        ),
    ]
