# Generated by Django 5.0.14 on 2026-04-22 05:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interests", "Interests"),
                            ("aptitudes", "Aptitudes"),
                            ("work_style", "Work Style"),
                            ("learning", "Learning"),
                            ("goals", "Goals"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("rating", "Rating"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ITRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("problem_solving_weight", models.IntegerField(default=5)),
                ("creativity_weight", models.IntegerField(default=5)),
                ("data_analysis_weight", models.IntegerField(default=5)),
                ("technical_depth_weight", models.IntegerField(default=5)),
                ("communication_weight", models.IntegerField(default=5)),
                ("visual_design_weight", models.IntegerField(default=5)),
                ("independent_work", models.BooleanField(default=False)),
                ("collaborative_work", models.BooleanField(default=True)),
                ("fast_paced", models.BooleanField(default=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner Friendly"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "avg_salary_uzs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "job_demand",
                    models.CharField(
                        choices=[
                            ("very_high", "Very High"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responses", models.JSONField(default=dict)),
                ("problem_solving_score", models.FloatField(default=0.0)),
                ("creativity_score", models.FloatField(default=0.0)),
                ("data_analysis_score", models.FloatField(default=0.0)),
                ("technical_depth_score", models.FloatField(default=0.0)),
                ("communication_score", models.FloatField(default=0.0)),
                ("visual_design_score", models.FloatField(default=0.0)),
                ("prefers_independent", models.BooleanField(blank=True, null=True)),
                ("prefers_collaborative", models.BooleanField(blank=True, null=True)),
                ("prefers_fast_paced", models.BooleanField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_assessment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_score", models.FloatField(help_text="0-100")),
                ("rank", models.IntegerField(help_text="1=top")),
                ("reasoning", models.TextField(blank=True, help_text="AI-generated")),
                ("user_selected", models.BooleanField(default=False)),
                ("user_viewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="career.itrole"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "rank"],
                "unique_together": {("user", "role")},
            },
        ),
    ]
