# Generated by Django 5.0.14 on 2026-03-24 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itrole",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
