# Generated by Django 5.2.9 on 2026-01-26 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('video', 'Video/Course'), ('book', 'Book'), ('documentation', 'Documentation'), ('article', 'Article/Blog Post'), ('tutorial', 'Tutorial'), ('interactive', 'Interactive Platform'), ('practice', 'Practice/Exercise')], help_text='Type of learning resource.', max_length=20, verbose_name='resource type')),
                ('title', models.CharField(help_text='Resource title.', max_length=300, verbose_name='title')),
                ('url', models.URLField(blank=True, help_text='Link to the resource.', max_length=500, null=True, verbose_name='URL')),
                ('author', models.CharField(blank=True, help_text='Author or creator name.', max_length=200, null=True, verbose_name='author')),
                ('platform', models.CharField(blank=True, help_text='Platform (YouTube, Udemy, W3Schools, etc.).', max_length=100, null=True, verbose_name='platform')),
                ('description', models.TextField(blank=True, help_text='Brief description of the resource.', null=True, verbose_name='description')),
                ('rating', models.FloatField(blank=True, default=0.0, help_text='Rating (0-5).', null=True, verbose_name='rating')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Difficulty level.', max_length=20, verbose_name='difficulty level')),
                ('estimated_duration', models.IntegerField(default=0, help_text='Estimated completion time in hours.', verbose_name='estimated duration (hours)')),
                ('is_free', models.BooleanField(default=True, help_text='Whether resource is free or paid.', verbose_name='is free')),
                ('language', models.CharField(default='en', help_text='Content language (en/ru/uz).', max_length=10, verbose_name='language')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether resource has been manually verified.', verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='skills.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'learning resource',
                'verbose_name_plural': 'learning resources',
                'db_table': 'learning_resources',
                'ordering': ['-is_verified', '-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('roadmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Roadmap title (e.g., "Path to Backend Developer").', max_length=200, verbose_name='title')),
                ('target_role', models.CharField(help_text='Target career role for this roadmap.', max_length=200, verbose_name='target role')),
                ('description', models.TextField(blank=True, help_text='AI-generated roadmap description and overview.', null=True, verbose_name='description')),
                ('total_estimated_hours', models.IntegerField(default=0, help_text='Total estimated learning hours for entire roadmap.', verbose_name='total estimated hours')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this roadmap is currently active.', verbose_name='is active')),
                ('completion_percentage', models.FloatField(default=0.0, help_text='Overall completion percentage (0-100).', verbose_name='completion percentage')),
                ('generated_by_ai', models.BooleanField(default=True, help_text='Whether roadmap was AI-generated or manually created.', verbose_name='generated by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'learning roadmap',
                'verbose_name_plural': 'learning roadmaps',
                'db_table': 'learning_roadmaps',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField(help_text='Order of this item in the roadmap (1, 2, 3...).', verbose_name='sequence order')),
                ('estimated_duration_hours', models.IntegerField(default=0, help_text='Estimated hours to complete this skill.', verbose_name='estimated duration (hours)')),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', help_text='Learning priority for this item.', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', help_text='Current learning status.', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='AI-generated notes or learning tips for this skill.', null=True, verbose_name='notes')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Skills that should be learned before this one.', related_name='dependent_items', to='learning.roadmapitem', verbose_name='prerequisites')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.learningroadmap', verbose_name='roadmap')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_items', to='skills.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'roadmap item',
                'verbose_name_plural': 'roadmap items',
                'db_table': 'roadmap_items',
                'ordering': ['roadmap', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='UserLearningProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', help_text='Learning status.', max_length=20, verbose_name='status')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress (0-100%).', verbose_name='progress percentage')),
                ('time_spent_hours', models.FloatField(default=0.0, help_text='Total time spent on this resource.', verbose_name='time spent (hours)')),
                ('notes', models.TextField(blank=True, help_text='User notes and observations.', null=True, verbose_name='notes')),
                ('rating', models.IntegerField(blank=True, help_text='User rating for this resource (1-5).', null=True, verbose_name='user rating')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.learningresource', verbose_name='resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user learning progress',
                'verbose_name_plural': 'user learning progress',
                'db_table': 'user_learning_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['skill'], name='learning_re_skill_i_59d33a_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['resource_type'], name='learning_re_resourc_f4a5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['difficulty_level'], name='learning_re_difficu_cbb08e_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['is_free'], name='learning_re_is_free_aadc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='learningroadmap',
            index=models.Index(fields=['user', 'is_active'], name='learning_ro_user_id_35c9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningroadmap',
            index=models.Index(fields=['target_role'], name='learning_ro_target__7b6cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmapitem',
            index=models.Index(fields=['roadmap', 'sequence_order'], name='roadmap_ite_roadmap_667e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmapitem',
            index=models.Index(fields=['status'], name='roadmap_ite_status_3e0a88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmapitem',
            unique_together={('roadmap', 'skill')},
        ),
        migrations.AddIndex(
            model_name='userlearningprogress',
            index=models.Index(fields=['user', 'status'], name='user_learni_user_id_ce7e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='userlearningprogress',
            index=models.Index(fields=['resource'], name='user_learni_resourc_35e0da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlearningprogress',
            unique_together={('user', 'resource')},
        ),
    ]
