"""
Learning App Models
===================
Models for learning roadmaps, roadmap items, learning resources, and user progress.

Tables:
- LearningRoadmap
- RoadmapItem
- LearningResource
- UserLearningProgress
"""

from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.users.models import User
from apps.skills.models import Skill


class LearningRoadmap(models.Model):
    """
    Personalized learning roadmap for users.
    Generated by AI based on skill gaps and target role.
    """
    
    roadmap_id = models.AutoField(
        primary_key=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='learning_roadmaps',
        verbose_name=_('user')
    )
    title = models.CharField(
        _('title'),
        max_length=200,
        help_text=_('Roadmap title (e.g., "Path to Backend Developer").')
    )
    target_role = models.CharField(
        _('target role'),
        max_length=200,
        help_text=_('Target career role for this roadmap.')
    )
    description = models.TextField(
        _('description'),
        blank=True,
        null=True,
        help_text=_('AI-generated roadmap description and overview.')
    )
    total_estimated_hours = models.IntegerField(
        _('total estimated hours'),
        default=0,
        help_text=_('Total estimated learning hours for entire roadmap.')
    )
    is_active = models.BooleanField(
        _('is active'),
        default=True,
        help_text=_('Whether this roadmap is currently active.')
    )
    completion_percentage = models.FloatField(
        _('completion percentage'),
        default=0.0,
        help_text=_('Overall completion percentage (0-100).')
    )
    generated_by_ai = models.BooleanField(
        _('generated by AI'),
        default=True,
        help_text=_('Whether roadmap was AI-generated or manually created.')
    )
    created_at = models.DateTimeField(
        _('created at'),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        _('updated at'),
        auto_now=True
    )
    
    class Meta:
        verbose_name = _('learning roadmap')
        verbose_name_plural = _('learning roadmaps')
        ordering = ['-is_active', '-created_at']
        db_table = 'learning_roadmaps'
        indexes = [
            models.Index(fields=['user', 'is_active']),
            models.Index(fields=['target_role']),
        ]
    
    def __str__(self):
        return f"{self.user.email} - {self.title}"
    
    def update_completion_percentage(self):
        """
        Calculate and update completion percentage based on roadmap items.
        """
        items = self.items.all()
        if not items:
            self.completion_percentage = 0.0
        else:
            completed = items.filter(status='completed').count()
            self.completion_percentage = (completed / items.count()) * 100
        self.save(update_fields=['completion_percentage'])


class RoadmapItem(models.Model):
    """
    Individual learning item/skill within a roadmap.
    Represents a step in the learning journey.
    """
    
    STATUS_CHOICES = [
        ('pending', _('Pending')),
        ('in_progress', _('In Progress')),
        ('completed', _('Completed')),
        ('skipped', _('Skipped')),
    ]
    
    PRIORITY_LEVELS = [
        ('high', _('High Priority')),
        ('medium', _('Medium Priority')),
        ('low', _('Low Priority')),
    ]
    
    item_id = models.AutoField(
        primary_key=True
    )
    roadmap = models.ForeignKey(
        LearningRoadmap,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name=_('roadmap')
    )
    skill = models.ForeignKey(
        Skill,
        on_delete=models.CASCADE,
        related_name='roadmap_items',
        verbose_name=_('skill')
    )
    sequence_order = models.IntegerField(
        _('sequence order'),
        help_text=_('Order of this item in the roadmap (1, 2, 3...).')
    )
    estimated_duration_hours = models.IntegerField(
        _('estimated duration (hours)'),
        default=0,
        help_text=_('Estimated hours to complete this skill.')
    )
    priority = models.CharField(
        _('priority'),
        max_length=20,
        choices=PRIORITY_LEVELS,
        default='medium',
        help_text=_('Learning priority for this item.')
    )
    status = models.CharField(
        _('status'),
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending',
        help_text=_('Current learning status.')
    )
    notes = models.TextField(
        _('notes'),
        blank=True,
        null=True,
        help_text=_('AI-generated notes or learning tips for this skill.')
    )
    prerequisites = models.ManyToManyField(
        'self',
        symmetrical=False,
        blank=True,
        related_name='dependent_items',
        verbose_name=_('prerequisites'),
        help_text=_('Skills that should be learned before this one.')
    )
    started_at = models.DateTimeField(
        _('started at'),
        blank=True,
        null=True
    )
    completed_at = models.DateTimeField(
        _('completed at'),
        blank=True,
        null=True
    )
    created_at = models.DateTimeField(
        _('created at'),
        auto_now_add=True
    )
    
    class Meta:
        verbose_name = _('roadmap item')
        verbose_name_plural = _('roadmap items')
        ordering = ['roadmap', 'sequence_order']
        db_table = 'roadmap_items'
        unique_together = [['roadmap', 'skill']]
        indexes = [
            models.Index(fields=['roadmap', 'sequence_order']),
            models.Index(fields=['status']),
        ]
    
    def __str__(self):
        return f"{self.roadmap.title} - Step {self.sequence_order}: {self.skill.skill_name}"
    
    def mark_as_completed(self):
        """
        Mark item as completed and update roadmap completion.
        """
        from django.utils import timezone
        
        self.status = 'completed'
        self.completed_at = timezone.now()
        self.save()
        
        # Update roadmap completion percentage
        self.roadmap.update_completion_percentage()
        
        # Add skill to user's skills
        from apps.skills.models import UserSkill
        UserSkill.objects.get_or_create(
            user=self.roadmap.user,
            skill=self.skill,
            defaults={
                'proficiency_level': 'beginner',
                'source': 'completed_learning'
            }
        )


class LearningResource(models.Model):
    """
    Learning resources (courses, videos, books, documentation).
    Recommended by AI for specific skills.
    """
    
    RESOURCE_TYPES = [
        ('video', _('Video/Course')),
        ('book', _('Book')),
        ('documentation', _('Documentation')),
        ('article', _('Article/Blog Post')),
        ('tutorial', _('Tutorial')),
        ('interactive', _('Interactive Platform')),
        ('practice', _('Practice/Exercise')),
    ]
    
    DIFFICULTY_LEVELS = [
        ('beginner', _('Beginner')),
        ('intermediate', _('Intermediate')),
        ('advanced', _('Advanced')),
        ('expert', _('Expert')),
    ]
    
    resource_id = models.AutoField(
        primary_key=True
    )
    skill = models.ForeignKey(
        Skill,
        on_delete=models.CASCADE,
        related_name='learning_resources',
        verbose_name=_('skill')
    )
    resource_type = models.CharField(
        _('resource type'),
        max_length=20,
        choices=RESOURCE_TYPES,
        help_text=_('Type of learning resource.')
    )
    title = models.CharField(
        _('title'),
        max_length=300,
        help_text=_('Resource title.')
    )
    url = models.URLField(
        _('URL'),
        max_length=500,
        blank=True,
        null=True,
        help_text=_('Link to the resource.')
    )
    author = models.CharField(
        _('author'),
        max_length=200,
        blank=True,
        null=True,
        help_text=_('Author or creator name.')
    )
    platform = models.CharField(
        _('platform'),
        max_length=100,
        blank=True,
        null=True,
        help_text=_('Platform (YouTube, Udemy, W3Schools, etc.).')
    )
    description = models.TextField(
        _('description'),
        blank=True,
        null=True,
        help_text=_('Brief description of the resource.')
    )
    rating = models.FloatField(
        _('rating'),
        default=0.0,
        blank=True,
        null=True,
        help_text=_('Rating (0-5).')
    )
    difficulty_level = models.CharField(
        _('difficulty level'),
        max_length=20,
        choices=DIFFICULTY_LEVELS,
        default='beginner',
        help_text=_('Difficulty level.')
    )
    estimated_duration = models.IntegerField(
        _('estimated duration (hours)'),
        default=0,
        help_text=_('Estimated completion time in hours.')
    )
    is_free = models.BooleanField(
        _('is free'),
        default=True,
        help_text=_('Whether resource is free or paid.')
    )
    language = models.CharField(
        _('language'),
        max_length=10,
        default='en',
        help_text=_('Content language (en/ru/uz).')
    )
    is_verified = models.BooleanField(
        _('verified'),
        default=False,
        help_text=_('Whether resource has been manually verified.')
    )
    created_at = models.DateTimeField(
        _('created at'),
        auto_now_add=True
    )
    
    class Meta:
        verbose_name = _('learning resource')
        verbose_name_plural = _('learning resources')
        ordering = ['-is_verified', '-rating', 'title']
        db_table = 'learning_resources'
        indexes = [
            models.Index(fields=['skill']),
            models.Index(fields=['resource_type']),
            models.Index(fields=['difficulty_level']),
            models.Index(fields=['is_free']),
        ]
    
    def __str__(self):
        return f"{self.skill.skill_name} - {self.title}"


class UserLearningProgress(models.Model):
    """
    Tracks user progress on individual learning resources.
    """
    
    STATUS_CHOICES = [
        ('started', _('Started')),
        ('in_progress', _('In Progress')),
        ('completed', _('Completed')),
        ('abandoned', _('Abandoned')),
    ]
    
    progress_id = models.AutoField(
        primary_key=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='learning_progress',
        verbose_name=_('user')
    )
    resource = models.ForeignKey(
        LearningResource,
        on_delete=models.CASCADE,
        related_name='user_progress',
        verbose_name=_('resource')
    )
    status = models.CharField(
        _('status'),
        max_length=20,
        choices=STATUS_CHOICES,
        default='started',
        help_text=_('Learning status.')
    )
    progress_percentage = models.IntegerField(
        _('progress percentage'),
        default=0,
        help_text=_('Progress (0-100%).')
    )
    time_spent_hours = models.FloatField(
        _('time spent (hours)'),
        default=0.0,
        help_text=_('Total time spent on this resource.')
    )
    notes = models.TextField(
        _('notes'),
        blank=True,
        null=True,
        help_text=_('User notes and observations.')
    )
    rating = models.IntegerField(
        _('user rating'),
        blank=True,
        null=True,
        help_text=_('User rating for this resource (1-5).')
    )
    started_at = models.DateTimeField(
        _('started at'),
        auto_now_add=True
    )
    completed_at = models.DateTimeField(
        _('completed at'),
        blank=True,
        null=True
    )
    updated_at = models.DateTimeField(
        _('updated at'),
        auto_now=True
    )
    
    class Meta:
        verbose_name = _('user learning progress')
        verbose_name_plural = _('user learning progress')
        ordering = ['-updated_at']
        db_table = 'user_learning_progress'
        unique_together = [['user', 'resource']]
        indexes = [
            models.Index(fields=['user', 'status']),
            models.Index(fields=['resource']),
        ]
    
    def __str__(self):
        return f"{self.user.email} - {self.resource.title} ({self.progress_percentage}%)"
    
    def mark_as_completed(self):
        """
        Mark resource as completed.
        """
        from django.utils import timezone
        
        self.status = 'completed'
        self.progress_percentage = 100
        self.completed_at = timezone.now()
        self.save()