# Generated by Django 5.2.9 on 2026-01-26 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(help_text='Normalized skill name in English.', max_length=100, unique=True, verbose_name='skill name')),
                ('category', models.CharField(choices=[('programming', 'Programming Language'), ('framework', 'Framework'), ('library', 'Library'), ('tool', 'Tool/Software'), ('database', 'Database'), ('cloud', 'Cloud Platform'), ('soft_skill', 'Soft Skill'), ('methodology', 'Methodology'), ('other', 'Other')], default='other', help_text='Skill category type.', max_length=50, verbose_name='category')),
                ('description', models.TextField(blank=True, help_text='Brief description of the skill.', null=True, verbose_name='description')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translations: {"ru": "Python", "uz": "Python"}', verbose_name='translations')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this skill has been manually verified.', verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skills',
                'ordering': ['skill_name'],
                'indexes': [models.Index(fields=['skill_name'], name='skills_skill_n_b9a819_idx'), models.Index(fields=['category'], name='skills_categor_b4d9fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('gap_id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('core', 'Core/Essential'), ('secondary', 'Secondary/Nice to Have')], default='secondary', help_text='How important this skill is for target role.', max_length=20, verbose_name='importance')),
                ('demand_priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', help_text='Priority based on market demand.', max_length=20, verbose_name='demand priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('learning', 'Currently Learning'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', help_text='Current learning status.', max_length=20, verbose_name='status')),
                ('target_proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Target proficiency level to achieve.', max_length=20, verbose_name='target proficiency')),
                ('estimated_learning_hours', models.IntegerField(default=0, help_text='Estimated hours needed to learn this skill.', verbose_name='estimated learning hours')),
                ('identified_at', models.DateTimeField(auto_now_add=True, verbose_name='identified at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='skills.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'skill gap',
                'verbose_name_plural': 'skill gaps',
                'db_table': 'skill_gaps',
                'ordering': ['-importance', '-demand_priority', 'skill__skill_name'],
                'indexes': [models.Index(fields=['user', 'status'], name='skill_gaps_user_id_bef47c_idx'), models.Index(fields=['importance', 'demand_priority'], name='skill_gaps_importa_9981b3_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_text', models.CharField(help_text='Original skill text as extracted.', max_length=200, verbose_name='original text')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], help_text='Language of original text.', max_length=2, verbose_name='language')),
                ('source', models.CharField(choices=[('hh.uz', 'hh.uz Job Posting'), ('cv', 'User CV'), ('manual', 'Manual Entry'), ('ai_extracted', 'AI Extracted')], help_text='Where this mapping came from.', max_length=20, verbose_name='source')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence in this mapping (0.0-1.0).', verbose_name='confidence score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('normalized_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='skills.skill', verbose_name='normalized skill')),
            ],
            options={
                'verbose_name': 'skill mapping',
                'verbose_name_plural': 'skill mappings',
                'db_table': 'skill_mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['original_text'], name='skill_mappi_origina_0f7ff3_idx'), models.Index(fields=['normalized_skill'], name='skill_mappi_normali_384bb1_idx')],
                'unique_together': {('original_text', 'language', 'source')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('user_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='User proficiency in this skill.', max_length=20, verbose_name='proficiency level')),
                ('years_of_experience', models.FloatField(default=0.0, help_text='Years of experience with this skill.', verbose_name='years of experience')),
                ('source', models.CharField(choices=[('cv', 'From CV'), ('manual', 'Manually Added'), ('completed_learning', 'Completed from Roadmap'), ('assessment', 'From Career Assessment')], default='manual', help_text='How this skill was added.', max_length=30, verbose_name='source')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is a primary/core skill for the user.', verbose_name='primary skill')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user skill',
                'verbose_name_plural': 'user skills',
                'db_table': 'user_skills',
                'ordering': ['-is_primary', '-proficiency_level', 'skill__skill_name'],
                'indexes': [models.Index(fields=['user', 'skill'], name='user_skills_user_id_ee319c_idx'), models.Index(fields=['proficiency_level'], name='user_skills_profici_7a0f4a_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
