# Generated by Django 5.2.9 on 2026-01-31 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(db_index=True, help_text="Canonical English name, e.g. 'Python', 'SQL', 'OOP'", max_length=100, unique=True, verbose_name='name (English)')),
                ('name_ru', models.CharField(blank=True, help_text="Russian translation, e.g. 'Питон', 'ООП'", max_length=100, null=True, verbose_name='name (Russian)')),
                ('name_uz', models.CharField(blank=True, help_text='Uzbek translation', max_length=100, null=True, verbose_name='name (Uzbek)')),
                ('normalized_key', models.CharField(db_index=True, editable=False, help_text="Auto-generated: 'python', 'oop', 'sql'", max_length=100, unique=True, verbose_name='normalized key')),
                ('category', models.CharField(choices=[('programming', 'Programming Language'), ('framework', 'Framework / Library'), ('database', 'Database'), ('tool', 'Tool / Software'), ('cloud', 'Cloud Platform'), ('methodology', 'Methodology / Practice'), ('soft_skill', 'Soft Skill'), ('other', 'Other')], default='other', max_length=30, verbose_name='category')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-reviewed and confirmed correct', verbose_name='verified')),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes about verification/merging', verbose_name='verification notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skills',
                'ordering': ['name_en'],
                'indexes': [models.Index(fields=['name_en'], name='skills_name_en_378a58_idx'), models.Index(fields=['normalized_key'], name='skills_normali_24e3cc_idx'), models.Index(fields=['category'], name='skills_categor_b4d9fb_idx'), models.Index(fields=['is_verified'], name='skills_is_veri_eb032c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('alias_id', models.AutoField(primary_key=True, serialize=False)),
                ('alias_text', models.CharField(db_index=True, help_text="Raw text as extracted: 'Python', 'Питон', 'PYTHON'", max_length=200, verbose_name='alias text')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='en', max_length=2, verbose_name='language')),
                ('source', models.CharField(choices=[('hh.uz', 'HH.uz API'), ('cv', 'User CV'), ('manual', 'Manual Entry'), ('ai_extracted', 'AI Extracted')], default='hh.uz', max_length=20, verbose_name='source')),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], db_index=True, default='unresolved', max_length=20, verbose_name='status')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score 0.00-1.00 for skill mapping', max_digits=3, null=True, verbose_name='confidence')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this alias appears in data', verbose_name='usage count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('skill', models.ForeignKey(blank=True, help_text='Resolved canonical skill (NULL until resolved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='skills.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'skill alias',
                'verbose_name_plural': 'skill aliases',
                'db_table': 'skill_aliases',
                'ordering': ['-usage_count', 'alias_text'],
                'indexes': [models.Index(fields=['skill'], name='skill_alias_skill_i_2bba04_idx'), models.Index(fields=['status'], name='skill_alias_status_caf41a_idx'), models.Index(fields=['language_code'], name='skill_alias_languag_817389_idx'), models.Index(fields=['alias_text'], name='skill_alias_alias_t_a4001f_idx'), models.Index(fields=['usage_count'], name='skill_alias_usage_c_fdc46f_idx')],
                'unique_together': {('alias_text', 'language_code', 'source')},
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('gap_id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('core', 'Core'), ('secondary', 'Secondary')], default='secondary', max_length=20, verbose_name='importance')),
                ('demand_priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('learning', 'Learning'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('identified_at', models.DateTimeField(auto_now_add=True, verbose_name='identified at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='skills.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'skill gap',
                'verbose_name_plural': 'skill gaps',
                'db_table': 'skill_gaps',
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('user_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='proficiency level')),
                ('years_of_experience', models.FloatField(default=0.0, verbose_name='years of experience')),
                ('source', models.CharField(choices=[('cv', 'From CV'), ('manual', 'Manual'), ('completed_learning', 'Completed Learning'), ('assessment', 'Career Assessment')], default='manual', max_length=30, verbose_name='source')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary skill')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user skill',
                'verbose_name_plural': 'user skills',
                'db_table': 'user_skills',
                'ordering': ['-is_primary', 'skill__name_en'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
