# Generated by Django 5.2.9 on 2026-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('library_or_package', 'Library / Package'), ('framework', 'Framework'), ('database', 'Database'), ('data_engineering', 'Data Engineering'), ('cloud_platform', 'Cloud Platform'), ('devops_infrastructure', 'DevOps / Infrastructure'), ('testing_qa', 'Testing / QA'), ('bi_analytics', 'BI / Analytics'), ('tools_software', 'Tools / Software'), ('design_creative', 'Design / Creative'), ('business_product_management', 'Business / Product Management'), ('security', 'Security'), ('networking', 'Networking'), ('operating_system', 'Operating System'), ('methodology_process', 'Methodology / Process'), ('soft_skill', 'Soft Skill'), ('domain_specific', 'Domain Specific'), ('other', 'Other')], default='other', max_length=30, verbose_name='category'),
        ),
    ]
