# Generated by Django 5.2.9 on 2026-02-04 12:44
# Modified to handle model move from analytics to skills app

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_update_skill_categories'),
        ('analytics', '0002_move_market_trend'),  # Ensure analytics migration runs first
    ]

    operations = [
        # Use SeparateDatabaseAndState to tell Django about the model
        # without actually creating the table (it already exists)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='MarketTrend',
                    fields=[
                        ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                        ('period', models.CharField(choices=[('7d', 'Last 7 days'), ('30d', 'Last 30 days'), ('90d', 'Last 90 days'), ('1y', 'Last year')], max_length=10, verbose_name='period')),
                        ('demand_score', models.FloatField(help_text='Normalized demand index (0–100)', verbose_name='demand score')),
                        ('job_count', models.IntegerField(help_text='Number of job postings containing this skill', verbose_name='job count')),
                        ('growth_rate', models.FloatField(help_text='Demand growth compared to previous period', verbose_name='growth rate (%)')),
                        ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='average salary')),
                        ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='calculated at')),
                        ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_trends', to='skills.skill', verbose_name='skill')),
                    ],
                    options={
                        'verbose_name': 'market trend',
                        'verbose_name_plural': 'market trends',
                        'db_table': 'market_trends',
                        'ordering': ['-calculated_at'],
                        'unique_together': {('skill', 'period')},
                    },
                ),
            ],
            database_operations=[],  # No database changes needed - table already exists
        ),
    ]
