# Generated by Django 5.2.9 on 2026-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_move_market_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markettrend',
            name='growth_rate',
            field=models.FloatField(blank=True, help_text='Demand growth compared to previous period. NULL if no previous data.', null=True, verbose_name='growth rate (%)'),
        ),
    ]
