# Generated by Django 5.2.9 on 2026-01-31 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='external job ID')),
                ('source', models.CharField(default='hh.uz', max_length=50, verbose_name='source')),
                ('original_language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='ru', max_length=2, verbose_name='original language')),
                ('job_title', models.CharField(max_length=255, verbose_name='job title')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='company')),
                ('job_category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('job_description', models.TextField(blank=True, verbose_name='description')),
                ('experience_required', models.CharField(blank=True, choices=[('no_experience', 'No Experience'), ('junior', 'Junior (1–3 years)'), ('mid', 'Mid (3–6 years)'), ('senior', 'Senior (6+ years)')], max_length=20, verbose_name='experience')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('project', 'Project-based')], default='full_time', max_length=20, verbose_name='employment type')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='min salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='max salary')),
                ('salary_currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('is_remote', models.BooleanField(default=False, verbose_name='remote')),
                ('posted_date', models.DateTimeField(verbose_name='posted date')),
                ('deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('job_url', models.URLField(max_length=500, verbose_name='job URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='scraped at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'job posting',
                'verbose_name_plural': 'job postings',
                'db_table': 'job_postings',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('job_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('core', 'Core'), ('secondary', 'Secondary')], default='core', max_length=20, verbose_name='importance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.jobposting')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='skills.skill')),
            ],
            options={
                'verbose_name': 'job skill',
                'verbose_name_plural': 'job skills',
                'db_table': 'job_skills',
                'unique_together': {('job_posting', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(related_name='job_postings', through='jobs.JobSkill', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='JobPostingTranslation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=2, verbose_name='language')),
                ('job_title', models.CharField(max_length=255, verbose_name='job title')),
                ('job_category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('job_description', models.TextField(blank=True, verbose_name='description')),
                ('requirements', models.TextField(blank=True, verbose_name='requirements')),
                ('responsibilities', models.TextField(blank=True, verbose_name='responsibilities')),
                ('translated_by', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='ai', max_length=20, verbose_name='translated by')),
                ('translation_quality', models.CharField(choices=[('raw', 'Raw AI'), ('reviewed', 'Reviewed'), ('verified', 'Verified')], default='raw', max_length=20, verbose_name='quality')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'job translation',
                'verbose_name_plural': 'job translations',
                'db_table': 'job_posting_translations',
                'unique_together': {('job_posting', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='JobSkillExtraction',
            fields=[
                ('extraction_id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('core', 'Core / Required'), ('secondary', 'Secondary / Nice-to-have')], default='core', max_length=20, verbose_name='importance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_extractions', to='skills.skillalias', verbose_name='skill alias')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_extractions', to='jobs.jobposting', verbose_name='job posting')),
            ],
            options={
                'verbose_name': 'job skill extraction',
                'verbose_name_plural': 'job skill extractions',
                'db_table': 'job_skill_extractions',
                'indexes': [models.Index(fields=['job_posting'], name='job_skill_e_job_pos_cc04fd_idx'), models.Index(fields=['alias'], name='job_skill_e_alias_i_8b4b12_idx')],
                'unique_together': {('job_posting', 'alias')},
            },
        ),
    ]
