# Generated by Django 5.2.9 on 2026-01-26 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(help_text='Job ID from source (e.g., hh.uz job ID).', max_length=100, unique=True, verbose_name='external job ID')),
                ('job_title', models.CharField(help_text='Position title.', max_length=200, verbose_name='job title')),
                ('company_name', models.CharField(help_text='Hiring company name.', max_length=200, verbose_name='company name')),
                ('job_category', models.CharField(blank=True, help_text='Job category (e.g., "Development", "Data Science").', max_length=100, null=True, verbose_name='job category')),
                ('experience_required', models.CharField(choices=[('no_experience', 'No Experience'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (5+ years)'), ('lead', 'Lead/Principal')], default='no_experience', help_text='Required experience level.', max_length=50, verbose_name='experience required')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary offered.', max_digits=12, null=True, verbose_name='minimum salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary offered.', max_digits=12, null=True, verbose_name='maximum salary')),
                ('salary_currency', models.CharField(default='UZS', help_text='Currency code (UZS, USD, etc.).', max_length=3, verbose_name='salary currency')),
                ('location', models.CharField(blank=True, help_text='Job location/city.', max_length=200, null=True, verbose_name='location')),
                ('job_description', models.TextField(help_text='Full job description text.', verbose_name='job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements and qualifications.', null=True, verbose_name='requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Job responsibilities.', null=True, verbose_name='responsibilities')),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks.', null=True, verbose_name='benefits')),
                ('posted_date', models.DateField(help_text='Date when job was posted.', verbose_name='posted date')),
                ('deadline_date', models.DateField(blank=True, help_text='Application deadline.', null=True, verbose_name='deadline date')),
                ('job_url', models.URLField(help_text='Link to original job posting.', max_length=500, verbose_name='job URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether job is still available.', verbose_name='is active')),
                ('is_remote', models.BooleanField(default=False, help_text='Whether position allows remote work.', verbose_name='remote work')),
                ('employment_type', models.CharField(blank=True, help_text='Full-time, Part-time, Contract, etc.', max_length=50, null=True, verbose_name='employment type')),
                ('source', models.CharField(default='hh.uz', help_text='Job board source.', max_length=50, verbose_name='source')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='scraped at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'job posting',
                'verbose_name_plural': 'job postings',
                'db_table': 'job_postings',
                'ordering': ['-posted_date', '-scraped_at'],
                'indexes': [models.Index(fields=['job_category'], name='job_posting_job_cat_432c1b_idx'), models.Index(fields=['experience_required'], name='job_posting_experie_794f87_idx'), models.Index(fields=['location'], name='job_posting_locatio_4c0773_idx'), models.Index(fields=['posted_date'], name='job_posting_posted__b2db8b_idx'), models.Index(fields=['is_active'], name='job_posting_is_acti_452b29_idx'), models.Index(fields=['external_job_id'], name='job_posting_externa_988ad2_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('job_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('core', 'Core/Required'), ('secondary', 'Secondary/Preferred'), ('nice_to_have', 'Nice to Have')], default='secondary', help_text='Importance of this skill for the job.', max_length=20, verbose_name='importance')),
                ('years_required', models.FloatField(blank=True, default=0.0, help_text='Minimum years of experience required.', null=True, verbose_name='years required')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, verbose_name='extracted at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.jobposting', verbose_name='job posting')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='skills.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'job skill',
                'verbose_name_plural': 'job skills',
                'db_table': 'job_skills',
                'ordering': ['-importance', 'skill__skill_name'],
                'indexes': [models.Index(fields=['job', 'skill'], name='job_skills_job_id_59b642_idx'), models.Index(fields=['importance'], name='job_skills_importa_7ccc03_idx')],
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_category', models.CharField(help_text='Job category (e.g., "Backend Development").', max_length=100, verbose_name='job category')),
                ('demand_score', models.FloatField(default=0.0, help_text='Demand score (0-10) based on job frequency.', verbose_name='demand score')),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Average salary for this category/skill.', max_digits=12, null=True, verbose_name='average salary')),
                ('salary_currency', models.CharField(default='UZS', max_length=3, verbose_name='salary currency')),
                ('job_count', models.IntegerField(default=0, help_text='Number of jobs requiring this skill/in this category.', verbose_name='job count')),
                ('growth_rate', models.FloatField(default=0.0, help_text='Growth rate compared to previous period (%).', verbose_name='growth rate')),
                ('analysis_period_start', models.DateField(help_text='Start date of analysis period.', verbose_name='analysis period start')),
                ('analysis_period_end', models.DateField(help_text='End date of analysis period.', verbose_name='analysis period end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('skill', models.ForeignKey(blank=True, help_text='Specific skill (optional, for skill-based trends).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_trends', to='skills.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'market trend',
                'verbose_name_plural': 'market trends',
                'db_table': 'market_trends',
                'ordering': ['-demand_score', '-created_at'],
                'indexes': [models.Index(fields=['job_category'], name='market_tren_job_cat_54589b_idx'), models.Index(fields=['skill'], name='market_tren_skill_i_dc70a6_idx'), models.Index(fields=['demand_score'], name='market_tren_demand__56721a_idx'), models.Index(fields=['analysis_period_start', 'analysis_period_end'], name='market_tren_analysi_506814_idx')],
            },
        ),
    ]
