# Generated by Django 5.0.14 on 2026-04-22 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        default="hh.uz", max_length=50, verbose_name="source"
                    ),
                ),
                (
                    "run_date",
                    models.DateField(
                        help_text="The calendar date this extraction covers.",
                        verbose_name="run date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                            ("startup", "Startup Catch-up"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="trigger",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "jobs_created",
                    models.IntegerField(default=0, verbose_name="jobs created"),
                ),
                (
                    "jobs_updated",
                    models.IntegerField(default=0, verbose_name="jobs updated"),
                ),
                (
                    "jobs_skipped",
                    models.IntegerField(default=0, verbose_name="jobs skipped"),
                ),
                (
                    "jobs_deactivated",
                    models.IntegerField(default=0, verbose_name="jobs deactivated"),
                ),
                (
                    "aliases_created",
                    models.IntegerField(default=0, verbose_name="aliases created"),
                ),
                ("errors_count", models.IntegerField(default=0, verbose_name="errors")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="celery task ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "extraction run",
                "verbose_name_plural": "extraction runs",
                "db_table": "extraction_runs",
                "ordering": ["-run_date", "-started_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="applied at"),
                ),
            ],
            options={
                "verbose_name": "job application",
                "verbose_name_plural": "job applications",
                "db_table": "job_applications",
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "external_job_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="external job ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="hh.uz", max_length=50, verbose_name="source"
                    ),
                ),
                (
                    "original_language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian"), ("uz", "Uzbek")],
                        default="ru",
                        max_length=2,
                        verbose_name="original language",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="job title"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="company"
                    ),
                ),
                (
                    "job_category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="category"
                    ),
                ),
                (
                    "job_description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "experience_required",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_experience", "No Experience"),
                            ("junior", "Junior (1–3 years)"),
                            ("mid", "Mid (3–6 years)"),
                            ("senior", "Senior (6+ years)"),
                        ],
                        max_length=20,
                        verbose_name="experience",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("project", "Project-based"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="employment type",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="min salary",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="max salary",
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="UZS", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(default=False, verbose_name="remote"),
                ),
                ("posted_date", models.DateTimeField(verbose_name="posted date")),
                (
                    "deadline_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deadline"
                    ),
                ),
                (
                    "job_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="job URL"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "listing_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="draft = not public; active = visible in job search; archived = closed listing.",
                        max_length=20,
                        verbose_name="listing status",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="view count"),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="scraped at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "job posting",
                "verbose_name_plural": "job postings",
                "db_table": "job_postings",
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                ("job_skill_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "importance",
                    models.CharField(
                        choices=[("core", "Core"), ("secondary", "Secondary")],
                        default="core",
                        max_length=20,
                        verbose_name="importance",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "job skill",
                "verbose_name_plural": "job skills",
                "db_table": "job_skills",
            },
        ),
        migrations.CreateModel(
            name="JobSkillExtraction",
            fields=[
                ("extraction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("core", "Core / Required"),
                            ("secondary", "Secondary / Nice-to-have"),
                        ],
                        default="core",
                        max_length=20,
                        verbose_name="importance",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "job skill extraction",
                "verbose_name_plural": "job skill extractions",
                "db_table": "job_skill_extractions",
            },
        ),
        migrations.AddConstraint(
            model_name="extractionrun",
            constraint=models.UniqueConstraint(
                fields=("source", "run_date"), name="unique_source_run_date"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="applicant",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Recruiter who created this listing on the platform; null for scraped jobs (e.g. hh.uz).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_job_postings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="posted by",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.jobposting",
                verbose_name="job posting",
            ),
        ),
        migrations.AddField(
            model_name="jobskill",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_skills",
                to="jobs.jobposting",
            ),
        ),
        migrations.AddField(
            model_name="jobskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_skills",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills",
            field=models.ManyToManyField(
                related_name="job_postings", through="jobs.JobSkill", to="skills.skill"
            ),
        ),
        migrations.AddField(
            model_name="jobskillextraction",
            name="alias",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_extractions",
                to="skills.skillalias",
                verbose_name="skill alias",
            ),
        ),
        migrations.AddField(
            model_name="jobskillextraction",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_extractions",
                to="jobs.jobposting",
                verbose_name="job posting",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job_posting", "-created_at"],
                name="job_applica_job_pos_a898a4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("job_posting", "applicant"), name="unique_job_applicant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobskill",
            unique_together={("job_posting", "skill")},
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["posted_by", "-posted_date"],
                name="job_posting_posted__a04c81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["source", "is_active"], name="job_posting_source_977638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobskillextraction",
            index=models.Index(
                fields=["job_posting"], name="job_skill_e_job_pos_cc04fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobskillextraction",
            index=models.Index(fields=["alias"], name="job_skill_e_alias_i_8b4b12_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="jobskillextraction",
            unique_together={("job_posting", "alias")},
        ),
    ]
