# Generated by Django 5.0.14 on 2026-02-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='hh.uz', max_length=50, verbose_name='source')),
                ('run_date', models.DateField(help_text='The calendar date this extraction covers.', verbose_name='run date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('startup', 'Startup Catch-up')], default='scheduled', max_length=20, verbose_name='trigger')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('jobs_created', models.IntegerField(default=0, verbose_name='jobs created')),
                ('jobs_updated', models.IntegerField(default=0, verbose_name='jobs updated')),
                ('jobs_skipped', models.IntegerField(default=0, verbose_name='jobs skipped')),
                ('aliases_created', models.IntegerField(default=0, verbose_name='aliases created')),
                ('errors_count', models.IntegerField(default=0, verbose_name='errors')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='celery task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'extraction run',
                'verbose_name_plural': 'extraction runs',
                'db_table': 'extraction_runs',
                'ordering': ['-run_date', '-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.UniqueConstraint(fields=('source', 'run_date'), name='unique_source_run_date'),
        ),
    ]
