# Generated by Django 5.0.14 on 2026-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_extraction_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrun',
            name='jobs_deactivated',
            field=models.IntegerField(default=0, verbose_name='jobs deactivated'),
        ),
    ]
