# Generated by Django 5.0.14 on 2026-03-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobposting_posted_by"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobposting",
            new_name="job_posting_posted__a04c81_idx",
            old_name="job_post_posted_by_idx",
        ),
        migrations.RenameIndex(
            model_name="jobposting",
            new_name="job_posting_source_977638_idx",
            old_name="job_post_source_act_idx",
        ),
    ]
