# Generated by Django 5.0.14 on 2026-03-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_listing_jobapplication"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="jobapplication",
            new_name="job_applica_job_pos_a898a4_idx",
            old_name="job_applicat_job_pos_7b8c7f_idx",
        ),
    ]
