# Generated by Django 5.2.9 on 2026-01-31 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('onboarding', 'Onboarding / Career Assessment'), ('roadmap', 'Learning Roadmap'), ('career', 'Career Advice'), ('help', 'General Help')], help_text='Type of conversation/assistance', max_length=20, verbose_name='context type')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When conversation was closed/completed', null=True, verbose_name='ended at')),
                ('is_active', models.BooleanField(default=True, help_text='Is this conversation still ongoing?', verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'chatbot conversation',
                'verbose_name_plural': 'chatbot conversations',
                'db_table': 'chatbot_conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10, verbose_name='sender type')),
                ('message_text', models.TextField(help_text='Message content', verbose_name='message text')),
                ('context_data', models.JSONField(blank=True, help_text='Additional context like skills, roles, intent, etc.', null=True, verbose_name='context data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_messages', to='chatbot.chatbotconversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'chatbot message',
                'verbose_name_plural': 'chatbot messages',
                'db_table': 'chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbotconversation',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_con_user_id_3141f9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotconversation',
            index=models.Index(fields=['-started_at'], name='chatbot_con_started_51736b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='chatbot_mes_convers_90de13_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['sender_type'], name='chatbot_mes_sender__4e061d_idx'),
        ),
    ]
