# Generated by Django 5.0.14 on 2026-04-28 02:27

from django.db import migrations
from pgvector.django import VectorExtension 

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        VectorExtension()
    ]
