# Generated by Django 5.0.14 on 2026-04-25 00:00

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("jobs", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="JobVector",
            fields=[
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vector",
                        serialize=False,
                        to="jobs.jobposting",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                (
                    "summary",
                    models.TextField(
                        help_text="Compact summary: title, company, skills, salary, experience"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "job_vectors",
            },
        ),
        migrations.CreateModel(
            name="SkillVector",
            fields=[
                (
                    "skill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vector",
                        serialize=False,
                        to="skills.skill",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "skill_vectors",
            },
        ),
    ]
