"""
Projects App Models
===================
backend/apps/projects/models.py

AI-generated portfolio project ideas for users.
Tracks user project completion status.
"""

from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from apps.skills.models import Skill


class ProjectIdea(models.Model):
    """
    Portfolio project ideas generated by AI.
    Helps users build practical experience.
    """
    
    DIFFICULTY_CHOICES = [
        ('beginner', _('Beginner')),
        ('intermediate', _('Intermediate')),
        ('advanced', _('Advanced')),
    ]
    
    project_id = models.AutoField(primary_key=True)
    
    title = models.CharField(
        _('title'),
        max_length=200
    )
    
    description = models.TextField(
        _('description'),
        help_text=_('Detailed project description and learning objectives')
    )
    
    target_role = models.CharField(
        _('target role'),
        max_length=100,
        help_text=_('Which career role this project is designed for')
    )
    
    difficulty_level = models.CharField(
        _('difficulty level'),
        max_length=20,
        choices=DIFFICULTY_CHOICES,
        default='beginner'
    )
    
    estimated_hours = models.PositiveIntegerField(
        _('estimated hours'),
        help_text=_('Estimated time to complete (in hours)')
    )
    
    created_at = models.DateTimeField(
        _('created at'),
        auto_now_add=True
    )
    
    # Many-to-many with skills through ProjectSkill
    skills = models.ManyToManyField(
        Skill,
        through='ProjectSkill',
        related_name='project_ideas'
    )
    
    class Meta:
        db_table = 'project_ideas'
        ordering = ['difficulty_level', 'title']
        verbose_name = _('project idea')
        verbose_name_plural = _('project ideas')
    
    def __str__(self):
        return f"{self.title} ({self.get_difficulty_level_display()})"
    
    def get_core_skills(self):
        """Get core skills required for this project."""
        return self.project_skills.filter(importance='core').select_related('skill')
    
    def get_secondary_skills(self):
        """Get secondary/optional skills."""
        return self.project_skills.filter(importance='secondary').select_related('skill')


class ProjectSkill(models.Model):
    """
    Skills required for each project.
    Links projects to skills with importance level.
    """
    
    IMPORTANCE_CHOICES = [
        ('core', _('Core / Required')),
        ('secondary', _('Secondary / Optional')),
    ]
    
    project_skill_id = models.AutoField(primary_key=True)
    
    project = models.ForeignKey(
        ProjectIdea,
        on_delete=models.CASCADE,
        related_name='project_skills',
        verbose_name=_('project')
    )
    
    skill = models.ForeignKey(
        Skill,
        on_delete=models.CASCADE,
        related_name='project_skills',
        verbose_name=_('skill')
    )
    
    importance = models.CharField(
        _('importance'),
        max_length=20,
        choices=IMPORTANCE_CHOICES,
        default='core'
    )
    
    class Meta:
        db_table = 'project_skills'
        unique_together = [('project', 'skill')]
        verbose_name = _('project skill')
        verbose_name_plural = _('project skills')
    
    def __str__(self):
        return f"{self.project.title} → {self.skill.name_en} ({self.importance})"


class UserProject(models.Model):
    """
    User's project work and completion status.
    Tracks portfolio building progress.
    """
    
    STATUS_CHOICES = [
        ('planned', _('Planned')),
        ('in_progress', _('In Progress')),
        ('completed', _('Completed')),
    ]
    
    user_project_id = models.AutoField(primary_key=True)
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user_projects',
        verbose_name=_('user')
    )
    
    project = models.ForeignKey(
        ProjectIdea,
        on_delete=models.CASCADE,
        related_name='user_projects',
        verbose_name=_('project')
    )
    
    status = models.CharField(
        _('status'),
        max_length=20,
        choices=STATUS_CHOICES,
        default='planned'
    )
    
    github_url = models.URLField(
        _('GitHub URL'),
        max_length=500,
        blank=True,
        help_text=_('Link to project repository')
    )
    
    live_demo_url = models.URLField(
        _('live demo URL'),
        max_length=500,
        blank=True,
        help_text=_('Link to deployed/live demo')
    )
    
    started_at = models.DateTimeField(
        _('started at'),
        null=True,
        blank=True
    )
    
    completed_at = models.DateTimeField(
        _('completed at'),
        null=True,
        blank=True
    )
    
    notes = models.TextField(
        _('notes'),
        blank=True,
        help_text=_('Personal notes, learnings, challenges faced')
    )
    
    class Meta:
        db_table = 'user_projects'
        unique_together = [('user', 'project')]
        ordering = ['-started_at']
        verbose_name = _('user project')
        verbose_name_plural = _('user projects')
    
    def __str__(self):
        return f"{self.user.username} → {self.project.title} ({self.status})"
    
    def is_completed(self):
        """Check if project is completed."""
        return self.status == 'completed'
    
    def completion_percentage(self):
        """Calculate completion percentage based on status."""
        status_percentage = {
            'planned': 0,
            'in_progress': 50,
            'completed': 100
        }
        return status_percentage.get(self.status, 0)